---
- name: Installing build dependencies (all)
  become: true
  package:
    name: "{{ dependencies.build.all }}"
    state: absent
  when: dependencies.build.all is defined
  tags:
    - dependencies

- name: Installing build dependencies (os_family)
  become: true
  package:
    name: "{{ dependencies['build'][ansible_os_family + '-family'] }}"
    state: absent
  when: dependencies['build'][ansible_os_family + '-family'] is defined
  tags:
    - dependencies

- name: Installing build dependencies (distribution)
  become: true
  package:
    name: "{{ dependencies['build'][ansible_distribution] }}"
    state: absent
  when: dependencies['build'][ansible_distribution] is defined
  tags:
    - dependencies
