---
- name: Converge
  hosts: all
  tasks:
    - include_role:
        name: jonsible.filter_plugins

    - name: Include buildspecs
      include_vars:
        file: buildspec.yml

    - include_role:
        name: builder
        tasks_from: builder.yml
