---
- name: Converge
  hosts: all
  vars_files:
    - buildspec.yml
  tasks:
    - include_role:
        name: jonsible.filter_plugins

    - include_vars:
        file: buildspec.yml

    - include_role:
        name: builder
        tasks_from: builder.yml
