---
- name: Converge
  hosts: all
  tasks:
    - include_role:
        name: jonsible.filter_plugins

    - name: Creating users
      become: true
      user:
        name: "jscherrerl"
        shell: /bin/bash

    - include_vars:
        file: ../default/buildspec.yml

    - include_role:
        name: builder
        tasks_from: builder.yml
      vars:
        owner: jscherrerl
        prefix: /home/jscherrerl/.local
