---
- name: Converge
  hosts: all
  vars_files:
    - ../default/buildspec.yml
  tasks:
    - include_role:
        name: jonsible.filter_plugins

    - name: Creating users
      become: true
      user:
        name: "jscherrerl"
        shell: /bin/bash

    - include_role:
        name: builder
      vars:
        owner: jscherrerl
        prefix: /home/jscherrerl/.local
